    org $0


    include "src/ports.inc"
    include "src/equals.inc"
    include "src/ram_addrs.inc"
;
; +-------------------------------------------------------------------------+
; |      This file was generated by The Interactive Disassembler (IDA)      |
; |           Copyright (c) 2022 Hex-Rays, <support@hex-rays.com>           |
; |                      ChinaPYG, 2022 Happy New Year                      |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : 5A5497F47BF3892D60476151494B8E5B7949E6DB728ED513D162095D54DE1B9A
; Input MD5    : D3293EBAAA7F4EB2A6766B68A0FB4609
; Input CRC32  : 3F888CF4
; Processor       : 68020
; Target assembler: 680x0 Assembler in MRI compatible mode
; This file should be compiled with "as -M"
; ===========================================================================
; Segment type: Pure code
; segment "ROM"
; ROM segment
                dc.l System_Stack&$FFFFFF
                dc.l Reset
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
ConsoleName:    dc.b 'SEGA GENESIS    ' ; DATA XREF: ROM:000002F4   r
                                        ; ROM:000002FA   r
CopyRight:      dc.b '(C)SEGA 1990.MAY'
DomesticName:   dc.b 'GENESIS OS                                      '
OverseasName:   dc.b 'GENESIS OS                                      '
ProductCode:    dc.b 'OS 00000000-00'
Checksum:       dc.w $5B74
Peripherials:   dc.b '                '
RomStart:       dc.l         0
RomEnd:         dc.l Padding+$4B
RamStart:       dc.l M68K_RAM&$FFFFFF
RamEnd:         dc.l unk_FFFFFF&$FFFFFF
SramCode:       dc.b $20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20
ModemCode:      dc.b $20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20
Reserved:       dc.b $20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20
                dc.b $20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20
                dc.b $20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20
                dc.b $20
CountryCode:    dc.b $55,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20
                dc.b $20,$20,$20
; ---------------------------------------------------------------------------
Reserv3F:                               ; CODE XREF: ROM:Reserv3F   j
                bra.s   Reserv3F
; ---------------------------------------------------------------------------
Reset:
                lea     SetupValues(pc),a5
                movem.l (a5)+,d5-d7/a0-a4
                move.b  -$10FF(a1),d0
                andi.b  #$F,d0
                beq.s   SkipSecurity
                move.l  #'SEGA',$2F00(a1)
SkipSecurity:                           ; CODE XREF: ROM:00000212   j
                move.w  (a4),d0
                moveq   #0,d0
                movea.l d0,a6
                move.l  a6,usp
                moveq   #$17,d1
loc_226:                                ; CODE XREF: ROM:0000022C   j
                move.b  (a5)+,d5
                move.w  d5,(a4)
                add.w   d7,d5
                dbf     d1,loc_226
                move.l  #$40000080,(a4)
                move.w  d0,(a3)
loc_238:                                ; CODE XREF: ROM:0000023E   j
                move.w  (a4),d4
                btst    #1,d4
                bne.s   loc_238
                move.l  #$81048F02,(a4)
                move.l  #$C0000000,(a4)
                moveq   #$1F,d3
loc_24E:                                ; CODE XREF: ROM:00000250   j
                move.l  d0,(a3)
                dbf     d3,loc_24E
                move.l  #$40000010,(a4)
                moveq   #$13,d4
loc_25C:                                ; CODE XREF: ROM:0000025E   j
                move.l  d0,(a3)
                dbf     d4,loc_25C
                moveq   #3,d5
loc_264:                                ; CODE XREF: ROM:00000268   j
                move.b  (a5)+,$11(a3)
                dbf     d5,loc_264
                bra.s   loc_2AA
; ---------------------------------------------------------------------------
SetupValues:    dc.w 0                  ; DATA XREF: ROM:Reset   o
                dc.w $8000
                dc.l $3FFF
                dc.w 0
                dc.w $100
                dc.l Z80_RAM
                dc.l IO_Z80BUS
                dc.l IO_Z80RES
                dc.l VDP_DATA
                dc.l VDP_CTRL
VDPInitValues:  dc.b   4
                dc.b $14
                dc.b $30 ; 0
                dc.b $3C ; <
                dc.b   7
                dc.b $6C ; l
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b $FF
                dc.b   0
                dc.b $81
                dc.b $37 ; 7
                dc.b   0
                dc.b   1
                dc.b   1
                dc.b   0
                dc.b   0
                dc.b $FF
                dc.b $FF
                dc.b   0
                dc.b   0
                dc.b $80
PSGInitValues:  dc.b $9F
                dc.b $BF
                dc.b $DF
                dc.b $FF
; ---------------------------------------------------------------------------
loc_2AA:                                ; CODE XREF: ROM:0000026C   j
                lea     (unk_FFC000).w,a0
                lea     aSege(pc),a1    ; " SEGE"
                movem.l (a1)+,d4-d7/a2-a6
                move.w  #$3F,d0 ; '?'
loc_2BA:                                ; CODE XREF: ROM:000002BC   j
                move.w  (a1)+,(a0)+
                dbf     d0,loc_2BA
                jsr     (unk_FFC000).w
loc_2C4:                                ; CODE XREF: ROM:loc_2C4   j
                bra.s   loc_2C4
; ---------------------------------------------------------------------------
aSege:          dc.b ' SEGE'            ; DATA XREF: ROM:000002AE   o
                dc.b $94, 0, 3, 0, 0, 0, $F7
aSega:          dc.b 'SEGA'
                dc.b 0, $A1, $40, 0, 0, $A1, $41, 1, 0, $C0, 0, 4, 0, $C0
                dc.b 0, 0, 0, $A1, 0, 1, 8, $D3, 0, 0, $BE, $B8
; ---------------------------------------------------------------------------
loc_2F0:
                btst    d0,d0
                beq.s   loc_316
                cmp.l   (ConsoleName).w,d4 ; "SEGA GENESIS    "
                bne.s   loc_302
                cmpi.b  #$41,(ConsoleName+4).w ; 'A' ; " GENESIS    "
                beq.s   loc_316
loc_302:                                ; CODE XREF: ROM:000002F8   j
                bclr    #0,(a3)
                move.b  (a6),d0
                andi.b  #$F,d0
                beq.s   locret_314
                move.l  #0,(a2)
locret_314:                             ; CODE XREF: ROM:0000030C   j
                rts
; ---------------------------------------------------------------------------
loc_316:                                ; CODE XREF: ROM:000002F2   j
                                        ; ROM:00000300   j
                bclr    #0,(a3)
                jsr     (loc_78C).l
                move.l  #$4C200000,(a4)
loc_326:                                ; CODE XREF: ROM:00000328   j
                move.l  (a1)+,(a5)
                dbf     d6,loc_326
                jsr     (loc_79C).l
                move.w  #$8144,(a4)
                move.w  #$3C,d0 ; '<'
                bsr.s   loc_35C
                move.w  #$8104,(a4)
                move.b  (a6),d0
                andi.b  #$F,d0
                beq.s   loc_34E
                move.l  #0,(a2)
loc_34E:                                ; CODE XREF: ROM:00000346   j
                bset    #0,(a3)
                moveq   #0,d0
                movea.l d0,a0
                movea.l (a0)+,sp
                movea.l (a0)+,a0
                jmp     (a0)
; ---------------------------------------------------------------------------
loc_35C:                                ; CODE XREF: ROM:0000033A   p
                                        ; ROM:00000364   j
                move.w  #$95CE,d1
loc_360:                                ; CODE XREF: ROM:loc_360   j
                dbf     d1,loc_360
                dbf     d0,loc_35C
                rts
; ---------------------------------------------------------------------------
Unk_Data:       dc.b 0, 1, $E, $EE, $E, $E8, 1, $11, $11, 0, $11, 0, 1
                dc.b $10, $11, 0, 1, $10, $11, 0, 1, $10, $11, $11, $11
                dc.b $10, $11, 0, 1, $10, $11, 0, 1, $10, 0, 0, 0, 0, $11
                dc.b $11, $11, 0, $11, 0, 1, $10, $11, 0, 1, $10, $11
                dc.b $11, $11, 0, $11, 0, 1, $10, $11, 0, 1, $10, $11
                dc.b $11, $11, 0, 0, 0, 0, 0, $11, $11, $11, $10, $11
                dc.b 0, 1, $10, $11, 0, 1, $10, $11, 0, 0, 0, $11, 0, 1
                dc.b $10, $11, 0, 1, $10, $11, $11, $11, $10, 0, 0, 0
                dc.b 0, $11, $11, $11, 0, $11, 0, 1, $10, $11, 0, 1, $10
                dc.b $11, 0, 1, $10, $11, 0, 1, $10, $11, 0, 1, $10, $11
                dc.b $11, $11, 0, 0, 0, 0, 0, $11, $11, $11, $10, $11
                dc.b 0, 0, 0, $11, 0, 0, 0, $11, $11, $11, 0, $11, 0, 0
                dc.b 0, $11, 0, 0, 0, $11, $11, $11, $10, 0, 0, 0, 0, $11
                dc.b $11, $11, $10, $11, 0, 0, 0, $11, 0, 0, 0, $11, $11
                dc.b $11, 0, $11, 0, 0, 0, $11, 0, 0, 0, $11, 0, 0, 0
                dc.b 0, 0, 0, 0, $11, $11, $11, $10, $11, 0, 1, $10, $11
                dc.b 0, 0, 0, $11, 0, $11, $10, $11, 0, 1, $10, $11, 0
                dc.b 1, $10, $11, $11, $11, $10, 0, 0, 0, 0, $11, 0, 1
                dc.b $10, $11, 0, 1, $10, $11, 0, 1, $10, $11, $11, $11
                dc.b $10, $11, 0, 1, $10, $11, 0, 1, $10, $11, 0, 1, $10
                dc.b 0, 0, 0, 0, 0, $11, $10, 0, 0, $11, $10, 0, 0, $11
                dc.b $10, 0, 0, $11, $10, 0, 0, $11, $10, 0, 0, $11, $10
                dc.b 0, 0, $11, $10, 0, 0, 0, 0, 0, 0, 0, 1, $10, 0, 0
                dc.b 1, $10, 0, 0, 1, $10, 0, 0, 1, $10, 0, 0, 1, $10
                dc.b 1, $10, 1, $10, 1, $11, $11, $10, 0, 0, 0, 0, $11
                dc.b 0, 1, $10, $11, 0, $11, 0, $11, $11, $10, 0, $11
                dc.b $11, $10, 0, $11, 0, $11, 0, $11, 0, 1, $10, $11
                dc.b 0, 1, $10, 0, 0, 0, 0, 1, $10, 0, 0, 1, $10, 0, 0
                dc.b 1, $10, 0, 0, 1, $10, 0, 0, 1, $10, 0, 0, 1, $10
                dc.b 0, 0, 1, $11, $11, $10, 0, 0, 0, 0, $11, 0, 1, $10
                dc.b $11, $10, $11, $10, $11, $11, $11, $10, $11, 1, 1
                dc.b $10, $11, 0, 1, $10, $11, 0, 1, $10, $11, 0, 1, $10
                dc.b 0, 0, 0, 0, $11, 0, 1, $10, $11, $10, 1, $10, $11
                dc.b $11, 1, $10, $11, 1, $11, $10, $11, 0, $11, $10, $11
                dc.b 0, 1, $10, $11, 0, 1, $10, 0, 0, 0, 0, $11, $11, $11
                dc.b $10, $11, 0, 1, $10, $11, 0, 1, $10, $11, 0, 1, $10
                dc.b $11, 0, 1, $10, $11, 0, 1, $10, $11, $11, $11, $10
                dc.b 0, 0, 0, 0, $11, $11, $11, $10, $11, 0, 1, $10, $11
                dc.b 0, 1, $10, $11, $11, $11, $10, $11, 0, 0, 0, $11
                dc.b 0, 0, 0, $11, 0, 0, 0, 0, 0, 0, 0, $11, $11, $11
                dc.b $10, $11, 0, 1, $10, $11, 0, 1, $10, $11, 0, 1, $10
                dc.b $11, 0, $11, $10, $11, 0, $11, $10, $11, $11, $11
                dc.b $10, 0, 0, 0, 0, $11, $11, $11, $10, $11, 0, 1, $10
                dc.b $11, 0, 1, $10, $11, $11, $11, 0, $11, 0, 1, $10
                dc.b $11, 0, 1, $10, $11, 0, 1, $10, 0, 0, 0, 0, $11, $11
                dc.b $11, $10, $11, 0, 1, $10, $11, 0, 0, 0, $11, $11
                dc.b $11, $10, 0, 0, 1, $10, $11, 0, 1, $10, $11, $11
                dc.b $11, $10, 0, 0, 0, 0, $11, $11, $11, $10, 0, $11
                dc.b $10, 0, 0, $11, $10, 0, 0, $11, $10, 0, 0, $11, $10
                dc.b 0, 0, $11, $10, 0, 0, $11, $10, 0, 0, 0, 0, 0, $11
                dc.b 0, 1, $10, $11, 0, 1, $10, $11, 0, 1, $10, $11, 0
                dc.b 1, $10, $11, 0, 1, $10, $11, 0, 1, $10, $11, $11
                dc.b $11, $10, 0, 0, 0, 0, $11, 0, 1, $10, $11, 0, 1, $10
                dc.b $11, 0, 1, $10, $11, 0, 1, $10, 1, $10, $11, 0, 0
                dc.b $11, $10, 0, 0, 1, 0, 0, 0, 0, 0, 0, $11, 0, 1, $10
                dc.b $11, 0, 1, $10, $11, 0, 1, $10, $11, 1, 1, $10, $11
                dc.b $11, $11, $10, $11, $10, $11, $10, $11, 0, 1, $10
                dc.b 0, 0, 0, 0, $11, 0, 1, $10, $11, 0, 1, $10, $11, $10
                dc.b $11, $10, 1, $11, $11, 0, $11, $10, $11, $10, $11
                dc.b 0, 1, $10, $11, 0, 1, $10, 0, 0, 0, 0, $11, 0, 1
                dc.b $10, $11, 0, 1, $10, $11, 0, 1, $10, 1, $10, $11
                dc.b 0, 0, $11, $10, 0, 0, $11, $10, 0, 0, $11, $10, 0
                dc.b 0, 0, 0, 0, $11, $11, $11, $10, 0, 0, $11, $10, 0
                dc.b 1, $11, 0, 0, $11, $10, 0, 1, $11, 0, 0, $11, $10
                dc.b 0, 0, $11, $11, $11, $10, 0, 0, 0, 0, 0, 0, 0, 0
                dc.b 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1
                dc.b $10, 0, 0, 1, $10, 0, 0, 0, 0, 0, 0, 2, $22, $22
                dc.b 0, $22, 0, 2, $20, $22, 0, 0, 0, 2, $22, $22, 0, 0
                dc.b 0, 2, $20, $22, 0, 2, $20, 2, $22, $22, 0, 0, 0, 0
                dc.b 0, 2, $22, $22, $20, $22, 0, 0, 0, $22, 0, 0, 0, $22
                dc.b $22, $22, 0, $22, 0, 0, 0, $22, 0, 0, 0, 2, $22, $22
                dc.b $20, 0, 0, 0, 0, 2, $22, $22, 0, $22, 0, 2, $20, $22
                dc.b 0, 0, 0, $22, 0, $22, $20, $22, 0, 2, $20, $22, 0
                dc.b 2, $20, 2, $22, $22, $20, 0, 0, 0, 0, 0, 2, $20, 0
                dc.b 0, $22, $22, 0, 0, $22, $22, 0, 2, $20, 2, $20, 2
                dc.b $20, 2, $20, $22, 0, 0, $22, $22, 2, $22, $22, 0
                dc.b 0, 0, 0
aProducedByOr:  dc.b '   produced by or'
                dc.b $FF
aUnderLicenseFr:dc.b ' under license from'
                dc.b $FF
aSegaEnterprise:dc.b 'sega,enterprises ltd'
                dc.b $7B ; {
                dc.b   0
; ---------------------------------------------------------------------------
loc_78C:                                ; CODE XREF: ROM:0000031A   p
                move.w  (a1)+,d0
                move.l  #$C0020000,(a4)
loc_794:                                ; CODE XREF: ROM:00000796   j
                move.w  (a1)+,(a5)
                dbf     d0,loc_794
                rts
; ---------------------------------------------------------------------------
loc_79C:                                ; CODE XREF: ROM:0000032C   p
                                        ; ROM:000007B2   j
                move.l  d5,(a4)
loc_79E:                                ; CODE XREF: ROM:000007AA   j
                moveq   #0,d1
                move.b  (a1)+,d1
                bmi.s   loc_7AC
                bne.s   loc_7A8
                rts
; ---------------------------------------------------------------------------
loc_7A8:                                ; CODE XREF: ROM:000007A4   j
                move.w  d1,(a5)
                bra.s   loc_79E
; ---------------------------------------------------------------------------
loc_7AC:                                ; CODE XREF: ROM:000007A2   j
                addi.l  #$1000000,d5
                bra.s   loc_79C
; ---------------------------------------------------------------------------
Padding:        dc.b $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
                dc.b $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
                dc.b $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
                dc.b $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
                dc.b $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
                dc.b $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
                dc.b $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
                dc.b $FF, $FF, $FF, $FF, $FF, $FF
; end of 'ROM'
